spring.application.name=notification-service
server.port=8084

# Notification Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Marat@123

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true